version: '3.8'

services:
  db:
    image: postgres:15
    container_name: repsy-postgres
    environment:
      POSTGRES_DB: repsy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: repsy-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  app:
    build:
      context: ./repsy-rest-api
    container_name: repsy-app
    depends_on:
      - db
      - minio
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/repsy
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      STORAGE_STRATEGY: file-system
    volumes:
      - ./packages:/app/packages

volumes:
  postgres_data:
  minio_data: